apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: ml
spec:
    environments:
        - name: production
          build:
              from: master
    components:
        - name: ml-api
          src: .
          ports:
              - name: http
                port: 5000
          publicPort: http
          environmentConfig:
              - environment: production
                replicas: 1
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "800m"
                  limits:
                    memory: "20Gi"
                    cpu: "10000m"
                variables:
                  DB_ACCOUNT_NAME: "rmrcdev"
          secrets:
              - DB_ACCOUNT_KEY
    dnsAppAlias:
        environment: production
        component: ml-api
